# GitHub Actions workflow for running Pylint on Python files.

# Copyright 2024 Qi Tianshi. All rights reserved.


name: Pylint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: ${{ !(github.event_name == 'pull_request' && (github.actor == 'dependabot[bot]' || github.event.pull_request.head.repo.full_name != github.repository)) }}
          token: ${{ secrets.DRCORE_GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint
        run: pylint --errors-only $(git ls-files '*.py')
