# GitHub Actions workflow for running Pylint on Python files.

# Copyright 2024 Qi Tianshi. All rights reserved.


name: Pylint

on:
  push:
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:

  # Whether the duty-rooster-core submodule should be checked out. For
  # security, it is not checked out if the workflow was triggered by a pull
  # pull request created by Dependabot or originating from an external fork.
  CHECKOUT_CORE: ${{ !(github.event_name == 'pull_request' && (github.actor == 'dependabot[bot]' || github.event.pull_request.head.repo.full_name != github.repository)) }}

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:

      # Checks out repos. Different tokens are provided depending on whether
      # submodules are checked out.
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: ${{ env.CHECKOUT_CORE }}
          token: ${{ env.CHECKOUT_CORE && secrets.DRCORE_GITHUB_TOKEN || github.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install pip dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint
        run: pylint --errors-only $(git ls-files '*.py')
